version: '3'
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.0-python3.8
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
    - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && 
        airflow users create --role Admin --username airflow --password airflow --email airflow@airflow.com --firstname airflow --lastname airflow &&
        chown -R airflow: /opt/airflow/logs &&
        touch /opt/airflow/logs/init_done

    depends_on:
        postgres:
          condition: service_healthy

  airflow-webserver:
    << : *airflow-common
    entrypoint: /bin/bash
    command: 
      - -c
      - |
        pip install python-dotenv &&
        pip install clickhouse-connect &&
        while [ ! -f /opt/airflow/logs/init_done ]; do
          echo "Waiting for init to complete..."
          sleep 10
        done &&
        airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    

  airflow-scheduler:
    << : *airflow-common
    container_name: airflow_scheduler
    entrypoint: /bin/bash
    command: 
      - -c
      - |
        pip install python-dotenv &&
        pip install clickhouse-connect &&
        while [ ! -f /opt/airflow/logs/init_done ]; do
          echo "Waiting for init to complete..."
          sleep 10
        done &&
        airflow scheduler
    
